services:

    dywee_faq.position_handler:
            class: Dywee\OrderBundle\Service\InvoiceReferenceManager
            arguments: [ ]
            tags:
                - { name: doctrine.event_listener, event: prePersist }

    ###########################
    #                         #
    #         SIDEBAR         #
    #                         #
    ###########################

    dywee_faq.admin_sidebar_listener:
        class: Dywee\FaqBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_faq.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_faq.sidebar_handler:
        class: Dywee\FaqBundle\Service\AdminSidebarHandler
        arguments: [ '@router' ]