services:

    ###########################
    #                         #
    #         SIDEBAR         #
    #                         #
    ###########################

    dywee_faq.admin_sidebar_listener:
        class: Dywee\FaqBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_faq.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_faq.sidebar_handler:
        class: Dywee\FaqBundle\Service\AdminSidebarHandler
        arguments: [ '@router' ]