<?php

namespace Dywee\FaqBundle\Repository;

/**
 * FaqItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqItemRepository extends \Doctrine\ORM\EntityRepository
{
}
